package ak.neocobblewatch.api.dto

import ak.neocobblewatch.activity.ActivitySnapshot
import kotlinx.serialization.Serializable

@Serializable
internal data class ActivityDto(
    val playTimeTicks: Long,
    val deaths: Int,
    val mobKills: Int,
    val fishCaught: Int,
    val damageDealt: Int,
    val damageTaken: Int,
    val damageBlocked: Int,
    val walkCm: Long,
    val sprintCm: Long,
    val flyCm: Long,
    val swimCm: Long,
    val jumps: Int,
    val sleepInBed: Int,
    val tradedWithVillager: Int,
    val blocksMined: Long,
    val itemsUsed: Long,
    val itemsCrafted: Long,
    val itemsBroken: Long,
    val killsMap: Map<String, Long>,
    val killedByMap: Map<String, Long>,
    val levelUps: Int,
    val evolutions: Int,
    val timesRidden: Int,
    val ridingLandCm: Long,
    val ridingAirCm: Long,
    val ridingLiquidCm: Long,
    val eggsCollected: Int,
    val eggsHatched: Int,
    val rodCasts: Int,
    val reelIns: Int,
    val released: Int,
    val raidsHosted: Int,
    val raidsJoined: Int,
    val raidsCompleted: Int,
    val raidTier1: Int,
    val raidTier2: Int,
    val raidTier3: Int,
    val raidTier4: Int,
    val raidTier5: Int,
    val badges: List<String>,
    val snapshotAt: Long,
) {
    companion object {
        val EMPTY = ActivityDto(
            playTimeTicks = 0, deaths = 0, mobKills = 0, fishCaught = 0,
            damageDealt = 0, damageTaken = 0, damageBlocked = 0,
            walkCm = 0, sprintCm = 0, flyCm = 0, swimCm = 0,
            jumps = 0, sleepInBed = 0, tradedWithVillager = 0,
            blocksMined = 0, itemsUsed = 0, itemsCrafted = 0, itemsBroken = 0,
            killsMap = emptyMap(), killedByMap = emptyMap(),
            levelUps = 0, evolutions = 0, timesRidden = 0,
            ridingLandCm = 0, ridingAirCm = 0, ridingLiquidCm = 0,
            eggsCollected = 0, eggsHatched = 0, rodCasts = 0, reelIns = 0, released = 0,
            raidsHosted = 0, raidsJoined = 0, raidsCompleted = 0,
            raidTier1 = 0, raidTier2 = 0, raidTier3 = 0, raidTier4 = 0, raidTier5 = 0,
            badges = emptyList(), snapshotAt = 0,
        )
    }
}

@Serializable
internal data class ActivityResponse(val data: ActivityDto)

internal fun ActivitySnapshot.toDto() = ActivityDto(
    playTimeTicks = playTimeTicks,
    deaths = deaths,
    mobKills = mobKills,
    fishCaught = fishCaught,
    damageDealt = damageDealt,
    damageTaken = damageTaken,
    damageBlocked = damageBlocked,
    walkCm = walkCm,
    sprintCm = sprintCm,
    flyCm = flyCm,
    swimCm = swimCm,
    jumps = jumps,
    sleepInBed = sleepInBed,
    tradedWithVillager = tradedWithVillager,
    blocksMined = blocksMined,
    itemsUsed = itemsUsed,
    itemsCrafted = itemsCrafted,
    itemsBroken = itemsBroken,
    killsMap = killsMap,
    killedByMap = killedByMap,
    levelUps = levelUps,
    evolutions = evolutions,
    timesRidden = timesRidden,
    ridingLandCm = ridingLandCm,
    ridingAirCm = ridingAirCm,
    ridingLiquidCm = ridingLiquidCm,
    eggsCollected = eggsCollected,
    eggsHatched = eggsHatched,
    rodCasts = rodCasts,
    reelIns = reelIns,
    released = released,
    raidsHosted = raidsHosted,
    raidsJoined = raidsJoined,
    raidsCompleted = raidsCompleted,
    raidTier1 = raidTier1,
    raidTier2 = raidTier2,
    raidTier3 = raidTier3,
    raidTier4 = raidTier4,
    raidTier5 = raidTier5,
    badges = badges,
    snapshotAt = snapshotAt,
)
